services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\SimpleAccountingBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Resources}'

    KimaiPlugin\SimpleAccountingBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
